language: node_js
node_js:
- node
script:
- npm run coverage
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  email: oshimish@gmail.com
  api_key:
    secure: Cr1LDTAwjqmG+TthFTYKdmQpdad6+F/oPDdBRdvdb8nTetH0DHgweIAMWIlIgGEUsPBLzduXqs0KTguFfjdFVcutJes+BfeSN8KB64omOB/0JVFYtvvbRUtxTcjiZEZTDf867weUp3YyvixOtDX/4OWvNtkGXoEzLWCUlc5zsDn2IWdv+7idWZINH0YRVkFegI8ZmAejzP2WpRTTuWF7nY/8Z5kHsfeV+gJl1iHOkIbU73AF9YbjROLmqK1sB06bRLvOTROdWRYl8EzCP3Zl/CF2djR3ndiRdZwcTDFnza3bMUoK/xmg93ICyuS9VwW2PZcrvz02HPAcCYN+H+6d9IZHleI67Qh+1Nf6GjWpwp6iofCDhFHZxw8m+ooUWTv2wQjkSN4sy5M3xS/C/cH4M/KIqitOsxbVov8p88GxtiypMjQImzWJFCxbOxJrSE65jevE6JOqQVACykXhUtQE5AKgJbvwo5NwOfXS+ae39aeiB+P13UT5dlzyX6fJ5xHVetlVpBNlesD4Un5kglaYmjKYv+KuLaDcrNE8xGYJcUeZHmmvzS0yWi1VQkwC3ybuEqamN31n+O9URZzTmaHw1XmpoSePQytxrG//Iti5l24oNODHx/2cRkbHgJ/8/BK71R0/V9DW7mmEtTFg4+MhtN0NBfY6ylqJEIZhtic900A=
  on:
    tags: true
    repo: oshimish/dreamspell-math
